### ISSUE TITLE
After grid layout, want to expand tile for comment section, resize window taking long

### ISSUE THREAD

**Issue by geekimposter** [germanysbestkeptsecret/Wookmark-jQuery#156]
Hi,

I have page of about 100 images, the tiles are laid out fine.  If a user clicks on the comment button, I append a chat section to the bottom of the tile and then call "$(window).trigger('resize');" to make the tile bigger for the chat section.  When I have less than 50 images loaded, the resize works fine and quick.  Since I implemented infinite scroll, the window resize call takes a lot longer when there are more than 50 images.  

Is there another way (besides window resize) to make the tile bigger when someone clicks on the chat button?

Thanks!

**Comment by Sebobo** [comment]
No response so I will close this
