### ISSUE TITLE
flexible example not fullwidth with one column

### ISSUE THREAD

**Issue by piotrku** [germanysbestkeptsecret/Wookmark-jQuery#176]
If you change the browser width to one column of images, as long as you change the window width the images take the width of the browser window, but when you then hit the reload button, the column of images takes the default width instead of the window width - not filling the whole space
It doesn't happen with two or more columns. 
I was trying to:
$('#tiles').trigger('refreshWookmark');
after reload but I couldn't make it work with one column

**Comment by Sebobo** [comment]
Should be better now with 2.0
