### ISSUE TITLE
V2.0 refreshWookmark 

### ISSUE THREAD

**Issue by ram-you** [germanysbestkeptsecret/Wookmark-jQuery#184]
Hi Sebastian, 1000 Bravos for the V2.0.

I think that <b>$('#myElementContainer').wookmark(options)</b> doesn't work anymore, use  <b>wookmark = new Wookmark('#myElementContainer'[, options ])</b> instead.

In the same logic use <b>wookmark.layout(true)</b> instead of <b>$('#myElementContainer').trigger('refreshWookmark')</b>

Am I right ?

**Comment by Sebobo** [comment]
Both should work fine. I want to support the old way too.
I still need to work a bit on the documentation for this.

**Comment by ram-you** [comment]
:thumbsup:
