### ISSUE TITLE
IE8: unable to get property 'initItems': object is null of undefined

### ISSUE THREAD

**Issue by MichaelVdheeren** [germanysbestkeptsecret/Wookmark-jQuery#189]
Anyone else using IE8 getting this error with v2.0. Having a hard time to pinpoint what it is exactly. Did not have this with previous versions.

**Comment by Sebobo** [comment]
Hi,

I did some testing with IE8 before I released 2.0.

Do you get that error with your implementation or in of the examples?

**Comment by MichaelVdheeren** [comment]
I guess with my implementation, but it's completely based on the infinite scroll example you provided

**Comment by Sebobo** [comment]
Just tested again with Win7 and IE8 but I cannot recreate the bug.
When you open the endless scroll example in the plugins folder, you get the same error?

**Comment by Sebobo** [comment]
IE8 won't be supported anymore.
