### ISSUE TITLE
JS Error from line 748

### ISSUE THREAD

**Issue by andywarren** [germanysbestkeptsecret/Wookmark-jQuery#192]
Just installed the plugin. JS error right out of the box. I initially stared with with .min version, and had the error, so switched to the wookmark.js non-minified version, and the same error persists. See the screenshot please.
![screen shot 2015-05-21 at 4 02 05 pm](https://cloud.githubusercontent.com/assets/1619596/7758941/0f34d78a-ffd3-11e4-9f8f-563f52db2601.png)

**Comment by Sebobo** [comment]
Hi,

was it one of the examples or your own code?
If so could you please show your initialisation js code?

Thanks

**Comment by wgallop99** [comment]
Having this same issue with the wookmark.js file, after utilizing the module in a drupal view. Once added and saved, the page is filled with json.

**Comment by Sebobo** [comment]
@wgallop99 can you copy your initialisation code of the plugin here?
Then I can help :)

**Comment by andywarren** [comment]
What do you mean by "installation code"? I could not get this to work and due to time constraints moved on to a different solution, but I can still try to assist in figuring this out in case others run into the issue. 

This is the entire code from the file wookmark.js that I was receiving the error on: https://gist.github.com/anonymous/4afab5fbcc138510e4ca

This is how I initiated the plugin: `jQuery('.taxPageRecipeWrapper').wookmark();`

**Comment by Sebobo** [comment]
@andywarren thanks for your feedback. The last line was the important one.
Were there multiple `taxPageRecipeWrapper` elements on the page?

**Comment by andywarren** [comment]
Yes, there are multiple `<div class="taxPageRecipeWrapper>...</div>` elements on the page.

**Comment by Sebobo** [comment]
@andywarren thanks so much, I had an error there. Should be fixed with the new 2.0.1.

**Comment by andywarren** [comment]
@Sebobo Awesome, thanks for the quick responses. I will mark the plugin for future use again!
