### ISSUE TITLE
Uncaught TypeError: $ is not a function

### ISSUE THREAD

**Issue by mr6volt** [germanysbestkeptsecret/Wookmark-jQuery#199]
I've been unable to make the plugin work.

I'm using Jquery 1.7.2,

and using this to initialize: $(".view-contents").wookmark();

I get the following error in the console: Uncaught TypeError: $ is not a function 
It is pointing at Line 748 of the wookmark js file.
 $(this).eq(i).wookmark(options);

**Comment by mr6volt** [comment]
FIXED IT!

Changed Line 748: $(this).eq(i).wookmark(options);
to: jQuery(this).eq(i).wookmark(options);

**Comment by Sebobo** [comment]
Hi, yes this error is known and fixed in 2.0.1.
