### ISSUE TITLE
virtual scrolling

### ISSUE THREAD

**Issue by martingg88** [germanysbestkeptsecret/Wookmark-jQuery#204]
can it attach/detach off-screen element when scrolling up/down in order to improve performance?

**Comment by martingg88** [comment]
any update on this issue?

**Comment by Sebobo** [comment]
Hi,

this is not yet implemented. There was another issue for that.
Didn't have time yet to think about how I will integrate this.

**Comment by Sebobo** [comment]
Duplicate of #174
