### ISSUE TITLE
The Wookmark layout is being update so many times

### ISSUE THREAD

**Issue by codehandling** [germanysbestkeptsecret/Wookmark-jQuery#207]
You can feel the effects of this on mobile screens, when you scroll down and every time after you scroll down manually, Wookmark will scroll up automatically to some height.

Not sure why, but this is probably because of layout updates, again and again.

I'm using Wookmark with images and imagesloaded.

**Comment by Sebobo** [comment]
Hi,

I don't see this issue with the endless scroll example on my iPhone.
Can you experience the same issue when you open that one?

**Comment by Sebobo** [comment]
No response so I close this
