### ISSUE TITLE
Adding a loading gif using Wookmark before images was loaded

### ISSUE THREAD

**Issue by jokero158** [germanysbestkeptsecret/Wookmark-jQuery#209]
How can I add a loader before images was loaded? Is there callbacks like start/end?

**Comment by Sebobo** [comment]
Hi,

the `imagesLoaded` plugin supports events.
You can see an example in the `example-load-images`.

**Comment by astbarc** [comment]
Hi,

To achieve this you can include a div element that contains the loading gif. After the images have loaded I hide this div.

  imagesLoaded('#container', function () { 
  jQuery('#loadingDiv').hide();
.....
