### ISSUE TITLE
Make wookmark available through npm?

### ISSUE THREAD

**Issue by jmwohl** [germanysbestkeptsecret/Wookmark-jQuery#212]
Any reason wookmark isn't available through npm? Or am I just missing it?

**Comment by Sebobo** [comment]
Nope, just registered it ;) https://www.npmjs.com/package/wookmark

**Comment by jmwohl** [comment]
@Sebobo Thanks! Unfortunately the postinstall script is erroring out, preventing it from being installed without adding --ignore-scripts (i.e. `npm install wookmark --ignore-scripts`)... you may want to fix that.
