### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by zb0t** [germanysbestkeptsecret/Wookmark-jQuery#214]
bower cache clean && node_modules/.bin/bower install && node_modules/.bin/grunt

**Comment by Sebobo** [comment]
@zb0t That should be fixed in the 2.1.0 release I did some days ago.

**Comment by zb0t** [comment]
@Sebobo Thanks for the reply. I attempted to install via npm yesterday.

**Comment by Sebobo** [comment]
Ok will check in a few days.

**Comment by Sebobo** [comment]
Ok, I published the latest version which no installs with problems.
