### ISSUE TITLE
Scroll up jump issue 

### ISSUE THREAD

**Issue by prajoshvm** [germanysbestkeptsecret/Wookmark-jQuery#215]
Hi
I have some issue with wookmark jquery plugin on Android chrome browser. I am using it for an e-commerce site with auto load products when scroll down. After full products loaded and when we scoll up it jumps to top of page automatically.
Can somebody suggest a solution for this ?

Thanks
Prajosh

**Comment by Sebobo** [comment]
Hi @prajoshvm,
do you have some example I could check?
Or can you show your js code you use?

Regards,
Sebastian

**Comment by prajoshvm** [comment]
Hi
pls check http://vps17554.inmotionhosting.com/~panemi5/sofas.html after
finish auto load try to scroll up, u can see issue

**Comment by prajoshvm** [comment]
Thanks
prajosh

**Comment by Sebobo** [comment]
Hi @prajoshvm,

you are completely reinitializing wookmark every time you reload more items.
This is not good for performance and could explain the behavior.

Take another look at the `example-endless-scroll`.
There the new items are appended and the existing wookmark instance just updates itself.
