### ISSUE TITLE
Tiles aren't showing in safari desktop and safari mobile/iOS

### ISSUE THREAD

**Issue by earthjibber** [germanysbestkeptsecret/Wookmark-jQuery#220]
Your plugin has always worked great for me however recently the tiles stopped showing in safari mobile and now on safari desktop. I have the tiles set to display:none to prevent the flickering until the js has loaded. Now it seems the the js for your plugin is not initializing and therefore not displaying the tiles in those specific browsers.

http://diningataltitude.com/vail-participants/2016-vail-participant/

**Comment by Sebobo** [comment]
Hi @earthjibber,

if this changed it must be something regarding your code and not the plugin I would say.

And in your link I cannot see anything using wookmark.

**Comment by earthjibber** [comment]
Got it working, i initialized it wrong. Also updated to the newest version.

thanks
