### ISSUE TITLE
Are window and document realy needed?

### ISSUE THREAD

**Issue by teawithfruit** [germanysbestkeptsecret/Wookmark-jQuery#224]
Hey,
Are window and document in the factory code realy needed?
If I remove them, the lib still works and my webpack build do not throw error anymore because of the none found modules "window" and "document".

Thx

**Comment by Sebobo** [comment]
I guess it could be removed. I added it at the time because of some "best practice" regarding testing with phantomjs and so on. But maybe things have changed again.

**Comment by teawithfruit** [comment]
Thanks for your instant answer. :)
