### ISSUE TITLE
Error JSON.parse

### ISSUE THREAD

**Issue by clementaf** [germanysbestkeptsecret/Wookmark-jQuery#226]
Hello,
I have this erros when i want to use filter:
JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 3.
This is for the line : "itemFilterClasses = JSON.parse(getData(item, 'filter-class', false, ''));"

When the li has the class "data-filter-class", i have this problem.

I don't find solution.

**Comment by Sebobo** [comment]
Hi,

what is the attribute value for your item which has `data-filter-class`?

**Comment by clementaf** [comment]
Hello, the error comes from me. Formatting PHP was not good. I solved the problems. Sorry for the loss of time. Anyway, I find your plugin that is really convenient.
